### ISSUE TITLE
Change roles.

### ISSUE THREAD

**Issue by GermanBluefox** [JoJ123/ioBroker.mihome-airpurifier#1]
Do you have predefined strings for that? E.g. ("auto", "silent", "manual")  
https://github.com/JoJ123/ioBroker.xiaomiairpurifier/blob/master/main.js#L106
https://github.com/JoJ123/ioBroker.xiaomiairpurifier/blob/master/main.js#L181
Please extend.

Please change "button.start" to another one:
https://github.com/JoJ123/ioBroker.xiaomiairpurifier/blob/master/main.js#L121 => "button.mode.silent"
https://github.com/JoJ123/ioBroker.xiaomiairpurifier/blob/master/main.js#L141 => "button.mode.favorite"

**Comment by JoJ123** [comment]
> Please change "button.start" to another one:
https://github.com/JoJ123/ioBroker.xiaomiairpurifier/blob/master/main.js#L121 => "button.mode.silent"
https://github.com/JoJ123/ioBroker.xiaomiairpurifier/blob/master/main.js#L141 => "button.mode.favorite"

This is clear for me, thx :)

> Do you have predefined strings for that? E.g. ("auto", "silent", "manual")
https://github.com/JoJ123/ioBroker.xiaomiairpurifier/blob/master/main.js#L106
https://github.com/JoJ123/ioBroker.xiaomiairpurifier/blob/master/main.js#L181
Please extend.

Here you would like to have instead of type: "string", that it can just match the three predefined strings?
Can you explain it a bit more please

**Comment by JoJ123** [comment]
Update: You mean something like this:
`adapter.setObjectNotExists(AIR_PURIFIER_INFORMATION + AIR_PURIFIER_MODE, {
    type: "state",
    common: {
      name: AIR_PURIFIER_MODE,
      type: "string",
      role: "text",
      read: true,
      write: false,
      states: {
        'auto' : 'Automatik',
        'silent' : 'Nacht',
        'favorite' : 'Manuell',
      }
    }
  });`

**Comment by GermanBluefox** [comment]
Yes. But in English:) Automatik => Auto and so on.

**Comment by JoJ123** [comment]
thx, done in #6
